AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 99

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/Documentation:
  Enabled: false
